# Generated by Django 2.2.5 on 2020-04-19 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tab_name', models.CharField(max_length=99)),
            ],
        ),
        migrations.CreateModel(
            name='Grant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField()),
                ('label', models.CharField(max_length=300, null=True)),
                ('text', models.TextField()),
                ('link', models.TextField(null=True)),
                ('org', models.TextField(null=True)),
                ('days', models.CharField(max_length=30, null=True)),
                ('rouble', models.CharField(max_length=30, null=True)),
                ('fond', models.TextField(null=True)),
                ('fond_link', models.TextField(null=True)),
                ('favorite', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-time',),
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type', to='main.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField()),
                ('grant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='main.Grant')),
            ],
        ),
        migrations.AddField(
            model_name='grant',
            name='grant_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grant', to='main.Type'),
        ),
        migrations.CreateModel(
            name='Fz44',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fz44id', models.CharField(max_length=100)),
                ('create_date', models.DateField()),
                ('link', models.TextField()),
                ('purchase_number', models.CharField(max_length=350)),
                ('purchase_object', models.TextField()),
                ('org_name', models.TextField()),
                ('placing_way', models.TextField(null=True)),
                ('start_date', models.CharField(max_length=350, null=True)),
                ('end_date', models.CharField(max_length=350, null=True)),
                ('place', models.TextField(null=True)),
                ('max_price', models.CharField(max_length=350, null=True)),
                ('currency', models.CharField(max_length=350, null=True)),
                ('finance_source', models.CharField(max_length=300, null=True)),
                ('aplication_guarantee', models.CharField(max_length=350, null=True)),
                ('contract_guarantee', models.CharField(max_length=350, null=True)),
                ('delivery', models.TextField(null=True)),
                ('delivery_place', models.TextField(null=True)),
                ('favorite', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('fz44_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fz44', to='main.Type')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Region')),
            ],
            options={
                'ordering': ('-create_date',),
            },
        ),
        migrations.CreateModel(
            name='Fz223',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=50)),
                ('create_date', models.DateField()),
                ('url_EIS', models.TextField(null=True)),
                ('url_VSRZ', models.TextField(null=True)),
                ('name', models.TextField()),
                ('full_name', models.TextField()),
                ('legal_address', models.TextField()),
                ('purchase_code_name', models.TextField()),
                ('place', models.TextField(null=True)),
                ('currency', models.CharField(max_length=50)),
                ('initial_sum', models.CharField(max_length=50, null=True)),
                ('submission_start_date', models.CharField(max_length=50, null=True)),
                ('submission_close_date', models.CharField(max_length=50, null=True)),
                ('favorite', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('fz223_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fz223', to='main.Type')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Region')),
            ],
            options={
                'ordering': ('-create_date',),
            },
        ),
        migrations.CreateModel(
            name='DigitalEconomy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(max_length=100, null=True)),
                ('date', models.DateField(null=True)),
                ('text', models.TextField()),
                ('link', models.TextField()),
                ('digitaleconomy_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digital_economy', to='main.Type')),
                ('favorite', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
    ]
