# Generated by Django 2.2.5 on 2019-12-07 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tab_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Grants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('label', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('link', models.CharField(max_length=300)),
                ('org', models.CharField(max_length=300)),
                ('days', models.CharField(max_length=30)),
                ('rouble', models.CharField(max_length=30)),
                ('fond', models.CharField(max_length=300)),
                ('fond_link', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type', to='main.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=300)),
                ('grant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='main.Grants')),
            ],
        ),
        migrations.AddField(
            model_name='grants',
            name='grant_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='main.Type'),
        ),
        migrations.CreateModel(
            name='Fz44',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fz44id', models.CharField(max_length=100)),
                ('link', models.TextField()),
                ('purchase_number', models.CharField(max_length=100)),
                ('purchase_object', models.CharField(max_length=300)),
                ('org_name', models.CharField(max_length=100)),
                ('placing_way', models.CharField(max_length=100)),
                ('start_date', models.CharField(max_length=100)),
                ('end_date', models.CharField(max_length=100)),
                ('place', models.TextField()),
                ('max_price', models.CharField(max_length=100)),
                ('currency', models.CharField(max_length=100)),
                ('finance_source', models.CharField(max_length=100)),
                ('aplication_guarantee', models.CharField(max_length=100)),
                ('contract_guarantee', models.CharField(max_length=100)),
                ('delivery', models.CharField(max_length=300)),
                ('delivery_place', models.CharField(max_length=300)),
                ('fz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fz44', to='main.Type')),
            ],
        ),
        migrations.CreateModel(
            name='Fz223',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=100)),
                ('create_date', models.DateTimeField()),
                ('url_EIS', models.TextField()),
                ('ulr_VSRZ', models.TextField()),
                ('name', models.CharField(max_length=300)),
                ('full_name', models.CharField(max_length=300)),
                ('legal_address', models.CharField(max_length=300)),
                ('purchase_code_name', models.CharField(max_length=300)),
                ('place', models.CharField(max_length=300)),
                ('currency', models.CharField(max_length=100)),
                ('initial_sum', models.CharField(max_length=100)),
                ('submission_start_date', models.CharField(max_length=100)),
                ('submission_close_date', models.CharField(max_length=100)),
                ('fz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fz223', to='main.Type')),
            ],
        ),
        migrations.CreateModel(
            name='Fcp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('card_name', models.CharField(max_length=300)),
                ('title', models.CharField(max_length=300)),
                ('lead', models.TextField()),
                ('link', models.CharField(max_length=300)),
                ('gp_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fcp', to='main.Type')),
            ],
        ),
    ]
