# Generated by Django 2.2.5 on 2019-12-07 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Grants',
            new_name='Grant',
        ),
        migrations.RenameModel(
            old_name='Links',
            new_name='Link',
        ),
    ]
