# Generated by Django 2.2.5 on 2019-12-07 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20191207_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcp',
            name='time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='fz223',
            name='create_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='grant',
            name='time',
            field=models.DateField(),
        ),
    ]
