# Generated by Django 2.2.5 on 2019-12-07 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20191207_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grant',
            name='days',
            field=models.CharField(blank=True, default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grant',
            name='fond',
            field=models.CharField(blank=True, default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grant',
            name='fond_link',
            field=models.CharField(blank=True, default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grant',
            name='label',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grant',
            name='link',
            field=models.CharField(blank=True, default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grant',
            name='org',
            field=models.CharField(blank=True, default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grant',
            name='rouble',
            field=models.CharField(blank=True, default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grant',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='grant',
            name='time',
            field=models.DateField(blank=True),
        ),
    ]
