# Generated by Django 2.2.5 on 2019-12-11 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20191207_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcp',
            name='card_name',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='fcp',
            name='lead',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='fcp',
            name='link',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='fcp',
            name='title',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='fz223',
            name='place',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='fz223',
            name='submission_close_date',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fz223',
            name='submission_start_date',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fz223',
            name='ulr_VSRZ',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='fz223',
            name='url_EIS',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='fz44',
            name='aplication_guarantee',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fz44',
            name='contract_guarantee',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fz44',
            name='delivery',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='fz44',
            name='delivery_place',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='fz44',
            name='end_date',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fz44',
            name='place',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='fz44',
            name='placing_way',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fz44',
            name='start_date',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='grant',
            name='days',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='grant',
            name='fond',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='grant',
            name='fond_link',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='grant',
            name='label',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='grant',
            name='link',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='grant',
            name='org',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='grant',
            name='rouble',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='grant',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='grant',
            name='time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(max_length=300),
        ),
    ]
