# Generated by Django 2.2.5 on 2019-12-13 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20191211_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcp',
            name='lead',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
