# Generated by Django 2.2.5 on 2019-12-13 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20191213_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcp',
            name='lead',
            field=models.TextField(null=True),
        ),
    ]
