# Generated by Django 2.2.5 on 2019-12-13 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20191213_1902'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fz223',
            old_name='ulr_VSRZ',
            new_name='url_VSRZ',
        ),
    ]
