# Generated by Django 2.2.5 on 2019-12-21 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20191213_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fz44',
            name='finance_source',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
