# Generated by Django 2.2.5 on 2019-12-21 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='fz223',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Region'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fz44',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Region'),
            preserve_default=False,
        ),
    ]
