# Generated by Django 2.2.7 on 2019-12-22 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20191221_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fz44',
            name='currency',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fz44',
            name='max_price',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
