# Generated by Django 2.2.7 on 2019-12-22 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20191222_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fz223',
            name='initial_sum',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
