# Generated by Django 2.2.7 on 2020-01-20 16:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_digitaleconomy_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='fz44',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2020, 1, 20, 16, 48, 57, 62129, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
