# Generated by Django 2.2.7 on 2020-01-20 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_fz44_create_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='digitaleconomy',
            old_name='type_name',
            new_name='digitaleconomy_name',
        ),
        migrations.RenameField(
            model_name='fcp',
            old_name='gp_name',
            new_name='fcp_name',
        ),
        migrations.RenameField(
            model_name='fz223',
            old_name='fz',
            new_name='fz223_name',
        ),
        migrations.RenameField(
            model_name='fz44',
            old_name='fz',
            new_name='fz44_name',
        ),
    ]