# Generated by Django 2.2.5 on 2020-01-21 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20200120_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grant',
            name='grant_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grant', to='main.Type'),
        ),
    ]
