# Generated by Django 2.2.5 on 2020-02-04 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20200123_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fz44',
            name='create_date',
        ),
    ]
