# Generated by Django 2.2.5 on 2020-02-08 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20200123_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='tab_name',
            field=models.CharField(max_length=99),
        ),
        migrations.AlterField(
            model_name='digitaleconomy',
            name='document_number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fcp',
            name='card_name',
            field=models.CharField(max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='fcp',
            name='link',
            field=models.CharField(max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='fcp',
            name='title',
            field=models.CharField(max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='fz223',
            name='currency',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='fz223',
            name='full_name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='fz223',
            name='initial_sum',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fz223',
            name='legal_address',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='fz223',
            name='name',
            field=models.CharField(max_length=700),
        ),
        migrations.AlterField(
            model_name='fz223',
            name='place',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='fz223',
            name='purchase_code_name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='fz223',
            name='registration_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='fz223',
            name='submission_close_date',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fz223',
            name='submission_start_date',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fz44',
            name='aplication_guarantee',
            field=models.CharField(max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='fz44',
            name='contract_guarantee',
            field=models.CharField(max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='fz44',
            name='currency',
            field=models.CharField(max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='fz44',
            name='delivery',
            field=models.CharField(max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='fz44',
            name='delivery_place',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='fz44',
            name='end_date',
            field=models.CharField(max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='fz44',
            name='finance_source',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='fz44',
            name='max_price',
            field=models.CharField(max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='fz44',
            name='org_name',
            field=models.CharField(max_length=350),
        ),
        migrations.AlterField(
            model_name='fz44',
            name='placing_way',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='fz44',
            name='purchase_number',
            field=models.CharField(max_length=350),
        ),
        migrations.AlterField(
            model_name='fz44',
            name='purchase_object',
            field=models.CharField(max_length=900),
        ),
        migrations.AlterField(
            model_name='fz44',
            name='start_date',
            field=models.CharField(max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='grant',
            name='label',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='link',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
