# Generated by Django 2.2.5 on 2020-03-08 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20200307_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcp',
            name='card_name',
            field=models.TextField(max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='fz223',
            name='full_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='fz223',
            name='legal_address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='fz223',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='fz44',
            name='delivery_place',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='fz44',
            name='org_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='fz44',
            name='purchase_object',
            field=models.TextField(),
        ),
    ]
