# Generated by Django 2.2.5 on 2020-03-09 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20200308_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='link',
            field=models.TextField(),
        ),
    ]
