# Generated by Django 2.2.5 on 2020-03-10 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20200309_1729'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='digitaleconomy',
            options={'ordering': ('-date',)},
        ),
        migrations.AlterModelOptions(
            name='fcp',
            options={'ordering': ('-time',)},
        ),
        migrations.AlterModelOptions(
            name='fz223',
            options={'ordering': ('-create_date',)},
        ),
        migrations.AlterModelOptions(
            name='fz44',
            options={'ordering': ('-create_date',)},
        ),
        migrations.AlterModelOptions(
            name='grant',
            options={'ordering': ('-time',)},
        ),
        migrations.AlterField(
            model_name='digitaleconomy',
            name='link',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='fcp',
            name='card_name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='fcp',
            name='link',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='fcp',
            name='title',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='fz223',
            name='place',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='fz44',
            name='delivery',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='fz44',
            name='placing_way',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='grant',
            name='fond',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='grant',
            name='fond_link',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='grant',
            name='link',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='grant',
            name='org',
            field=models.TextField(null=True),
        ),
    ]
