# Generated by Django 2.2.5 on 2020-03-28 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20200310_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fz223',
            name='purchase_code_name',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='Fcp',
        ),
    ]
