# Generated by Django 2.2.5 on 2020-03-24 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20200310_1613'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fcp',
        ),
    ]
